title: WiDS Kathmandu Datathon Workshop 2022
logo: /images/wids-matrix-stacked.jpg
show_downloads: false
description: Wids Kathmandu Datathon Workshop aims at providing hands-on training and mentorship for beginners and intermediates who have strong interest in data science.
theme: jekyll-theme-minimal
